package com.reactive.examples.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;

import java.sql.Timestamp;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Table("reportstate")
public class ReportState {
    //CREATE TABLE reportstate ( report_state_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    //report_status_id integer, report_details_id integer,
    //report_create_date timestamp, report_expire_date timestamp);
    @Id
    private Integer report_state_id;
    private Integer report_status_id;
    private Integer report_details_id;
    private Timestamp report_create_date;
    private Timestamp report_expire_date;
}
